fix: attachment ttl handling.

diff --git a/lib/bash-agent/ba-shell b/lib/bash-agent/ba-shell
--- a/lib/bash-agent/ba-shell
+++ b/lib/bash-agent/ba-shell
@@ -38,6 +38,10 @@ if [ -t 0 ]; then
     which pandoc > /dev/null 2>&1 && enable_pandoc=1
 fi
 
+# Setup env vars
+declare -x BA_AUTO_APPROVE="${BA_AUTO_APPROVE:-N}"
+
+# Setup temp files
 BA_AGENT_CONTEXT=$(mktemp --suffix=.json)
 BA_AGENT_TEMP_CONTEXT=$(mktemp --suffix=.json)
 BA_AGENT_TOOL_STDOUT=$(mktemp --suffix=.txt)
@@ -45,12 +49,15 @@ BA_AGENT_TOOL_STDERR=$(mktemp --suffix=.txt)
 
 response=
 answer=
+token_usage=0
 BA_LAST_MODEL=
 BA_LAST_SPEED=
 BA_LAST_PROMPT_SPEED=
 
 declare -a attachments
 attachments=()
+declare -a attachments_ttl
+attachments_ttl=()
 
 # --- LOGGING HELPER ---
 # Simply redirects all parameters to stderr
@@ -111,7 +118,7 @@ attach_instructions() {
 }
 
 # --- Load attachments ---
-# Loads the file specified in the attachments array, and builds a series of
+# Loads the files specified in the attachments array, and builds a series of
 # messages with the file contents.
 load_attachments() {
     messages='[]'
@@ -119,8 +126,10 @@ load_attachments() {
     for f in "${attachments[@]}"; do
         if [[ -f "$f" ]]; then
             messages=$( \
-                echo "$messages" | jq '. += [{role: "user", content: "\n\n--- File: " + $ARGS.positional[0] + " ---\n" + $ARGS.positional[1] }]' \
-                --args -- "$f" "$(grep -n '' "$f")")
+                echo "$messages" | jq '. += [{role: "user", content: "\n\n--- File: " + $ARGS.positional[0] + " ---\n" + $content }]' \
+                --rawfile content <(grep -n '' "$f") \
+                --args -- "$f" \
+            )
         fi
     done
 
@@ -130,13 +139,21 @@ load_attachments() {
 # --- Add attachment ---
 # Adds a file to the list of the attachments
 add_attachment() {
-    if [[ -f $1 ]]; then
-        attachments+=("$1")
-        return 0
+    file="$1"
+
+    if [[ -f "$file" ]]; then
+        if [[ " ${attachments[*]} " =~ [[:space:]]${file}[[:space:]] ]]; then
+            return 0
+        fi
+
+        attachments+=("$file")
+        attachments_ttl+=(5)
     else
-        echo "read: file not found $1" >&2
+        echo "read: file not found $file" >&2
         return 1
     fi
+
+    return 0
 }
 
 # --- Ask approval ---
@@ -158,28 +175,54 @@ ask_approval() {
         return 1
     fi
 
-    retval="User rejected with feedback: ""$approval"
+    retval="User rejected with feedback: $approval"
     return 2
+}
+
+# --- Trim context ---
+trim_context() {
+    # Drop attachments older than 5 turns
+    # TODO: Drop messages older than 10 turns
+    # TODO: Compact context every 10 messages.
+    for ((i=0; i<${#attachments_ttl[@]}; i++)); do
+        attachments_ttl[$i]=$((${attachments_ttl[$i]} - 1))
+
+        if [[ ${attachments_ttl[$i]} -eq 0 ]]; then
+            unset "attachments[$i]"
+            unset "attachments_ttl[$i]"
+        fi
+    done
+
+    # Compaction
+    attachments=("${attachments[@]}")
+    attachments_ttl=("${attachments_ttl[@]}")
 }
 
 # --- Calls llm, updates the context and prints the answer ---
 # Since the piped prompt is processed outside the agent loop, this factors code
 # that would otherwise be repeated.
 call_llm_updatecontext_and_print() {
+    # Before sending, context should be trimmed
+    trim_context
+
     response=$( \
         cat "$BA_AGENT_CONTEXT" | \
-        jq '.messages += $ARGS.positional[0]' \
-        --jsonargs -- "$(load_attachments)" | \
+        jq '.messages += $messages[0]' \
+        --slurpfile messages <(load_attachments) | \
         "$BA_PATH"/ba-curl \
     )
 
-    answer=$(echo "$response" | jq '.choices[0].message | {role: .role, content: .content, tool_calls: .tool_calls}')
+    answer="$(echo "$response" | jq '.choices[0].message | {role: .role, content: .content, reasoning_content: .reasoning_content, tool_calls: .tool_calls}')"
 
     # Extract model name and generation speed from response
     BA_LAST_MODEL=$(echo "$response" | jq -r '.model // empty')
     BA_LAST_PROMPT_SPEED=$(echo "$response" | jq -r '.timings.prompt_per_second // empty')
     BA_LAST_SPEED=$(echo "$response" | jq -r '.timings.predicted_per_second // empty')
+    token_usage=$(echo "$response" | jq -r '.usage.prompt_tokens // empty')
 
+    log "Token usage: $token_usage"
+
+    # Update the context
     jq '.messages += [ $ARGS.positional[0] ]' \
         $BA_AGENT_CONTEXT \
         --jsonargs -- "$answer" > "$BA_AGENT_TEMP_CONTEXT"
@@ -203,6 +246,14 @@ call_tool() {
         echo "File $path was successfully attached."
     else
         "$BA_TOOLS_PATH"/"$tool" "$2"
+    fi
+
+    # After writing, we need to attach the
+    # file.
+    if [[ "$tool" == "write" ]]; then
+        path=$(echo "$2" | jq -r '.file')
+        add_attachment "$path"
+        echo "File $path was successfully attached."
     fi
 }
 
@@ -287,7 +338,9 @@ main() {
                 if [[ $is_a_tty == "1" ]]; then
                     log ""
                     "$BA_TOOLS_PATH"/$name -i "$arguments" | mdcat
+                fi
 
+                if [[ $is_a_tty == "1" && $BA_AUTO_APPROVE != "Y" ]]; then
                     set +e
                     feedback=
                     ask_approval feedback
