feat: read tool now attaches to chat context.

diff --git a/lib/bash-agent/ba-shell b/lib/bash-agent/ba-shell
--- a/lib/bash-agent/ba-shell
+++ b/lib/bash-agent/ba-shell
@@ -49,6 +49,9 @@ BA_LAST_MODEL=
 BA_LAST_SPEED=
 BA_LAST_PROMPT_SPEED=
 
+declare -a attachments
+attachments=()
+
 # --- LOGGING HELPER ---
 # Simply redirects all parameters to stderr
 log() {
@@ -85,11 +88,90 @@ mdcat() {
     fi
 }
 
+# --- Attach file ---
+# Permanently attaches a file to the chat context
+attach() {
+    ls "$1" &&
+        jq '.messages += [{role: "user", content: "\n\n--- File: " + $ARGS.positional[0] + " ---\n" + $ARGS.positional[1] }]' \
+        "$BA_AGENT_CONTEXT" \
+        --args -- "$1" "$(cat "$1")" > "$BA_AGENT_TEMP_CONTEXT" &&
+        swap_context
+}
+
+# --- Attach instructions ---
+# Permanently attaches current project agent instructions file to the chat
+# context.
+# If no instructions file is found just succedes silently.
+attach_instructions() {
+    attach ./AGENT.md || \
+    attach ./AGENTS.md || \
+    attach ./CLAUDE.md || \
+    attach ./.github/copilot-instructions.md || \
+    true
+}
+
+# --- Load attachments ---
+# Loads the file specified in the attachments array, and builds a series of
+# messages with the file contents.
+load_attachments() {
+    messages='[]'
+
+    for f in "${attachments[@]}"; do
+        if [[ -f "$f" ]]; then
+            messages=$( \
+                echo "$messages" | jq '. += [{role: "user", content: "\n\n--- File: " + $ARGS.positional[0] + " ---\n" + $ARGS.positional[1] }]' \
+                --args -- "$f" "$(grep -n '' "$f")")
+        fi
+    done
+
+    echo "$messages"
+}
+
+# --- Add attachment ---
+# Adds a file to the list of the attachments
+add_attachment() {
+    if [[ -f $1 ]]; then
+        attachments+=("$1")
+        return 0
+    else
+        echo "read: file not found $1" >&2
+        return 1
+    fi
+}
+
+# --- Ask approval ---
+# Asks the user to approve a tool call, optionally providing
+# steering feedback.
+ask_approval() {
+    local -n retval="$1"
+
+    approval=""
+
+    while [[ -z "$approval" ]]; do
+        read -r -e -p "Approve? Type Y, N or a message> " approval
+    done
+
+    if [[ "$approval" == "Y" || "$approval" == "y" ]]; then
+        return 0
+    elif [[ "$approval" == "N" || "$approval" == "n" ]]; then
+        retval="User rejected the tool call."
+        return 1
+    fi
+
+    retval="User rejected with feedback: ""$approval"
+    return 2
+}
+
 # --- Calls llm, updates the context and prints the answer ---
 # Since the piped prompt is processed outside the agent loop, this factors code
 # that would otherwise be repeated.
 call_llm_updatecontext_and_print() {
-    response=$(cat "$BA_AGENT_CONTEXT" | "$BA_PATH"/ba-curl)
+    response=$( \
+        cat "$BA_AGENT_CONTEXT" | \
+        jq '.messages += $ARGS.positional[0]' \
+        --jsonargs -- "$(load_attachments)" | \
+        "$BA_PATH"/ba-curl \
+    )
 
     answer=$(echo "$response" | jq '.choices[0].message | {role: .role, content: .content, tool_calls: .tool_calls}')
 
@@ -109,44 +191,19 @@ call_llm_updatecontext_and_print() {
     fi
 }
 
-# --- Attach file ---
-# Attaches a file to the chat context
-attach() {
-    ls "$1" &&
-        jq '.messages += [{role: "user", content: "\n\n--- File: " + $ARGS.positional[0] + " ---\n" + $ARGS.positional[1] }]' \
-        "$BA_AGENT_CONTEXT" \
-        --args -- "$1" "$(cat "$1")" > "$BA_AGENT_TEMP_CONTEXT" &&
-        swap_context
-}
+# --- Call tool ---
+# Calls a tool, forcing a builtin implementation for the builtins (read).
+call_tool() {
+    tool="$1"
 
-# --- Attach instructions ---
-# Attaches current project agent instructions file to the chat context.
-# If no instructions file is found just succedes silently.
-attach_instructions() {
-    attach ./AGENT.md || \
-    attach ./AGENTS.md || \
-    attach ./CLAUDE.md || \
-    attach ./.github/copilot-instructions.md || \
-    true
-}
-
-# --- Ask approval ---
-# Asks the user to approve a tool call, optionally providing
-# steering feedback.
-ask_approval() {
-    local -n retval="$1"
-
-    read -r -e -p "Approve? Type Y, N or a message> " approval
-
-    if [[ "$approval" == "Y" || "$approval" == "y" ]]; then
-        return 0
-    elif [[ "$approval" == "N" || "$approval" == "n" ]]; then
-        retval="User rejected the tool call."
-        return 1
+    if [[ "$tool" == "read" ]]; then
+        # Extract path
+        path=$(echo "$2" | jq -r '.file')
+        add_attachment "$path"
+        echo "File $path was successfully attached."
+    else
+        "$BA_TOOLS_PATH"/"$tool" "$2"
     fi
-
-    retval="User rejected with feedback: ""$approval"
-    return 2
 }
 
 # --- Main Script Logic ---
@@ -200,7 +257,11 @@ main() {
                 log "$(printf -- "------ %s - Prompt: %.2f t/s - Generation: %.2f t/s" "$BA_LAST_MODEL" "$BA_LAST_PROMPT_SPEED" "$BA_LAST_SPEED")"
             fi
             log "------ $PWD ------"
-            read -r -e -p "> " prompt
+            prompt=""
+
+            while [[ -z "$prompt" ]]; do
+                read -r -e -p "> " prompt
+            done
 
             jq '.messages += [{role: "user", content: $ARGS.positional[0] }]' \
                 "$BA_AGENT_CONTEXT" \
@@ -235,10 +296,9 @@ main() {
 
                     if [[ "$exit_status" == "0" ]]; then
                         set +e
-                        "$BA_TOOLS_PATH"/$name "$arguments" \
+                        call_tool "$name" "$arguments" \
                             > "$BA_AGENT_TOOL_STDOUT" \
-                            2>&1 | tee "$BA_AGENT_TOOL_STDERR"
-
+                            2> "$BA_AGENT_TOOL_STDERR"
                         exit_status=$?
                         set -e
                     else
@@ -247,7 +307,7 @@ main() {
                     fi
                 else
                     set +e
-                    "$BA_TOOLS_PATH"/$name "$arguments" \
+                    call_tool "$name" "$arguments" \
                         > "$BA_AGENT_TOOL_STDOUT" \
                         2> "$BA_AGENT_TOOL_STDERR"
 
